### ISSUE TITLE
Ability to use with Sora

### ISSUE THREAD

**Issue by Clairmince** [houtianze/libby-audiobook-exporter-browser-extension#2]
Is it possible to add the ability to download from Sora as well? It's essentially the same interface by the same company.

**Comment by houtianze** [comment]
Thanks for the feedback. Just Googled it, interesting, it's from OverDrive also. But I don't have an account to test, otherwise I think it's possible.

**Comment by Clairmince** [comment]
> Thanks for the feedback. Just Googled it, interesting, it's from OverDrive also. But I don't have an account to test, otherwise I think it's possible.

You can get a free account through several libraries. Notably, Audiobooksync will give a free account to anyone if you sign up on their website. There are several titles available year round through them. You can then add your local libraries if they are partnered with Sora.

**Comment by houtianze** [comment]
Sora extension published: https://chromewebstore.google.com/detail/sora-audiobook-exporter/encfiidbdjibjhlchleofknhelkobolc

**Comment by Amraan-Amjad** [comment]
> Audiobooksync

How could I get a free account on Sora

**Comment by Amraan-Amjad** [comment]
> Sora

Done
My bad
