### ISSUE TITLE
Include Release Date in .json file

### ISSUE THREAD

**Issue by wtfwjd8** [houtianze/libby-audiobook-exporter-browser-extension#6]
Can you grab the Release Date and include it in the openbook.json file?

**Comment by houtianze** [comment]
The `openbook.json` file is directly downloaded from libby.com , so I'd rather not touch its contents at all. And I don't recall seeing this information from the network traffic from libby.com.

**Comment by wtfwjd8** [comment]
Ah, I didn't know the file was coming from Libby directly, but that makes sense why I couldn't find where it was being put together. In that case I totally agree, I wouldn't attempt to manipulate its contents either. Thanks for the clarification!
