### ISSUE TITLE
error downloading books with comma characters in title

### ISSUE THREAD

**Issue by az-azza** [houtianze/libby-audiobook-exporter-browser-extension#8]
On macos downloading fails if book title contains comma character or possibly comma and space combination.

service-worker.js:105 Uncaught (in promise) Error: Invalid filename
await (async)
messageListener @ service-worker.js:142

**Comment by houtianze** [comment]
Thanks for the feedback. Can you please copy & paste the book name? The code already does some file name sanitizing, but I wasn't aware that comma plus space will cause issues on Mac.

**Comment by az-azza** [comment]
Both of these titles throw file naming error for me in the console for service-worker.js in macos:https://share.libbyapp.com/title/1863594https://share.libbyapp.com/title/4157162Its first thing after I click Export and i dont see a new book folder being created  in my downloads (i have chrome set to just download files without prompting target directory) so im assuming its failing on the first call to resolve target path for the cover picture with these books names.
-------- Original message --------From: Hou Tianze ***@***.***> Date: 2/20/24  2:40 PM  (GMT-05:00) To: houtianze/libby-audiobook-exporter-browser-extension ***@***.***> Cc: az-azza ***@***.***>, Author ***@***.***> Subject: Re: [houtianze/libby-audiobook-exporter-browser-extension] error
  downloading books with comma characters in title (Issue #8) 
Thanks for the feedback. Can you please copy & paste the book name? The code already does some file name sanitizing, but I wasn't aware that comma plus space will cause issues on Mac.

**Comment by houtianze** [comment]
Updated addon published.
